# Generated by Django 5.1 on 2024-09-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="modelo_sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_sucursal", models.CharField(max_length=100)),
                ("direccion_sucursal", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="modelo_departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_departamento", models.CharField(max_length=100)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sucursales.modelo_sucursal",
                    ),
                ),
            ],
        ),
    ]
